# this file contains the deploy playbooks.
#
---
- name: Create OSP objects
  hosts: localhost
  collections:
    - openstack.cloud
  vars_files:
  - group_vars/instances.yml

  roles:
  - role: provision


- name: Deploy, configure, and populate Postgres
  hosts: database_servers
  gather_facts: false
  become: true

  vars_files:
  - group_vars/database_servers.yml

  roles:
  - role: postgres

- name: Deploy, configure, and populate flask repo and virtualenv
  hosts: app_servers

  vars_files:
  - group_vars/app_servers.yml

  roles:
  - role: flask

- name: Deploy haproxy load balancer
  hosts: load_balancers
  gather_facts: false
  become: true

  vars_files:
  - group_vars/load_balancers.yml

  roles:
  - role: haproxy
